### PR TITLE
Add county ID, additional alert properties, and PlatformNotReady

### PR DESCRIPTION
**Pull request by jlverhagen**
Allowing county id codes as well as zone id codes should take care of the problem where people aren't getting any alerts or aren't getting all of the active alerts for their location.

The changes here will maintain backward compatibility for entering 'Z' zone id's as a one, two, or three digit number as currently documented. The issue I, and others, have found is many times there are active alerts that aren't being picked up by the weatheralerts custom component. The problem is actually with weather.gov and the 'Z' zone feeds. The 'Z' zone id feeds (from https://www.weather.gov/pimar/PubZone) don't seem to be properly updating and that results in no alerts in the feed even though there are active alerts being picked up via other sources. The 'C' county id feeds do appear to contain all of the alerts. The 'C' county id's can be found at https://alerts.weather.gov/ and then you click the County List link for your state/territory location to find the county id (which will probably different from the zone id, so be sure to look it up). Once the 'C' county id is found,  enter the full six character id in the YAML as the zone. The id is case sensitive (all letters should be capitalized).

The code changes will also allow for multiple id's to be specified, but there currently is no de-duplication to remove duplicate alerts from multiple id's. To use a 'C' county id or to use multiple id's, the full 6 character id must be used and is case sensitive (all letters should be capitalized). Multiple id's should be separated by a comma and contain no spaces.

### CODE REVIEW

**Comment by ntilley905** [comment]
Installed this on my HA instance and I'll wait to see if we get multiple alerts to test it out.

**Comment by jlverhagen** [comment]
I can confirm both the Zone and County IDs are unreliable when used with the weather.gov api endpoints. I'll look for another solution.

**Comment by jlverhagen** [comment]
After further review and testing, the reliability issue with the county IDs I previously experienced was due to Nginx web server errors on the servers that provide the weather.gov json weather alert feeds. It doesn't exactly give me strong confidence in the National Weather Service to know severe weather warnings may not arrive via Home Assistant notifications due to intermittent problems with Nginx web servers. 

(the following info is mostly notes for me to refer back to when I revisit this issue)

While the json feeds were unavailable for several hours on that particular day, I did note the atom/xml alert feeds appeared to be unaffected. It should be possible to use the atom/xml feeds as a backup source if the json feeds aren't working. Two obstacles need to be overcome to make that happen... 

1. A reliable way to determine if the json feeds are down or broken. 
2. Mapping the atom/xml alert attributes to the appropriate sensor attributes the json alert attributes are currently mapped to.

For 1, there may not be a 100% reliable way to make the determination. The feed may be broken but still return an empty valid json formatted feed. In that case, I'm thinking the easiest way would be to fetch the atom/xml feed if the json feed is empty or returns an error, just as a failsafe backup check. The other more robust way would be to fetch both the json and atom/xml feeds, compare them, and place all unique alerts from the combined feeds into the component sensor alerts object.

For 2, there are alert attributes that are available in the json feed that are not available in the atom/xml feed. Most notably, the NWSheadline attribute appears to be set for all alerts in the json feeds, but it doesn't exist in the atom/xml feeds. Some of these missing attributes may be able to be recreated using existing data in the atom/xml feed. The rest of the missing attributes would be set to None, and additional if/else checks would be needed in the yaml for the appropriate sensor attributes to account for the missing data.

**Comment by ludeeus** [comment]
I used to use the XML feed, which has a lot of issues on its own and should not be reintroduced here.

An option to cope with server issues will be to introduce an "Unavailable" state (This is how it works elsewhere in HA)

As for defining multiple zones in a single definition, I will not support that addition.
You can add multiple sensors which will be the correct way to do it and is in how other things in HA are defined.

Supporting both county and zone is fine by me, but it should be done by adding a new `type:` config option that takes 2 options `county` / `zone` (should be required)

For setting attributes that _may_ be unavailable in the json feed, use `data.get('attr')`  instead of `data['attr']` to have it handle attribute errors.

@jlverhagen ping me when you are ready for me to look into this.

**Comment by jlverhagen** [comment]
@ludeeus  Thanks for the suggestions and recommendations. I have updated the sensor.py to follow your suggestions and recommendations. I also added PlatformNotReady that may help with issues #27  and #31. Some of my additions with this pull request include additional alert properties that may satisfy issue #33.

Do you want me to keep my yaml packages in this pull request, remove them from the pull request, or move them to a new pull request? Should I add a _/packages_ directory to the repository and move the yaml packages there? The yaml packages include documentation in comments but will need further documentation for the less-technical Home Assistant users.

Once you approve the sensor.py changes, I can also go through the README.md documentation and update it to reflect the sensor.py changes and include that with this pull request as well. 

I have reverted some of my initial changes to make the pull request conform to your suggestions and recommendations, but I am not in total agreement when it comes to not allowing multiple county/zone IDs and not allowing the XML feed. I do agree that multiple geographical areas should be configured separately with multiple platform configurations, but if we can specify a zone and a county ID for the same geographical area then we can increase the reliability of the alerts received. It doesn't make much sense to have two platform configurations for the same geographical area. I have had at least two instances where the county json feed had active alerts and the zone json feed had none. If I only had the zone ID configured with weatheralerts, I would not have gotten any alerts in Home Assistant. I would assume the reverse is also possible (the zone feed contains alerts, while the county feed contains none), or even worse, if it happens both ways at random. And a similar reliability argument for the XML feed. I don't want to use the XML alert feed as an alternative to the json feeds, or as a supplement to working json feeds. Just use the XML feed as a backup for when the json feeds may not be working. If the json feeds are down and there are active alerts, I think most people would rather get those alerts from the XML feed instead of not getting any alerts at all. I've had instances where the json feeds were timing out or returning NGINX error pages instead of valid json feeds for hours at a time, but the XML feeds were still working. I won't request this specific feature to be included in this pull request, but I'd like to see the reliability of something as important as severe weather alerts to be as good as it can be. I may be able to accomplish this completely in yaml using the feedparser, but I would rather implement it in sensor.py.

**Comment by ludeeus** [comment]
I have an idea... 
Please contact me on Discord `Ludeeus#4212`

**Pull request merged**
